name: DevSecOps Pipeline (Frontend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo docker-compose pull
          sudo docker-compose up -d --force-recreate --remove-orphans

  dast-scan:
    runs-on: ubuntu-latest
    needs: deploy-job # Ensure dast-scan runs after deploy-job
    permissions:
      security-events: write
      actions: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://app.36.lebondeveloppeur.net/' # Replace with your app's URL
          docker_options: "--user $(id -u):$(id -g)"
          fail_action: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap_reports
          path: |
            report_*.json
            report_*.html
          retention-days: 2
