name: DevSecOps Pipeline Frontend-app

env:
  BUILD_NUMBER: ${{ github.run_number }}
  IMAGE_NAME: frontend-image
  VITE_API_URL: http://localhost:3001

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force

      - name: Run unit tests
        run: npm test

  sast-scan:
    runs-on: ubuntu-latest
    needs: test-job
    timeout-minutes: 10
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: https://sonarcloud.io
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-actio
